### ISSUE TITLE
How are the ROIs linked over time?

### ISSUE THREAD

**Issue by junting** [HaozhiQi/RPIN#1]
Hi,

Thank you very much for sharing your code! I just see that the ROIs locations are input to the model together with the first 4 frames, however, I am sure how are the ROIs feature are cat over time? How we can know that two ROIs belong to the same object? Are the ROIs annotated with an instance ID?

Best,

**Comment by HaozhiQi** [comment]
Yes, the input RoIs are annotated with instance ID.

For the simulator case, we can just use the ground-truth.
For real-world videos, we compare the color similarity and position distance to track each object.

**Comment by junting** [comment]
OK! Thanks for your reply.
