### ISSUE TITLE
About the pretrained model of baselines

### ISSUE THREAD

**Issue by dingmyu** [HaozhiQi/RPIN#3]
Hi Haozhi,

Very nice work! I am currently following your work. Could you share the pre-training models or training codes of other baselines in Tab. 1 (VIN, OM, CVP, IN)?

Thanks,
Mingyu

**Comment by HaozhiQi** [comment]
Hello, sorry I just saw your issue.

Originally, I didn't post those because I think those code will make the code structure unnecessarily complicated. But I can make another branch to show how to get baseline results. 

I'm a bit busy these days, but I can first post the related code here by tomorrow and then release the model asap.

**Comment by HaozhiQi** [comment]
Hi, here is the update [commit](https://github.com/HaozhiQi/RPIN/commit/69656d4e844998ab30032f1430c7c206e7427441). The entry point is the `configs/realb/rpin.yaml`.

```
USE_VIN_FEAT: False  # set true to use VIN; But VIN need some special configuration, see below.
ROI_MASKING: False  # set true to use OM
ROI_CROPPING: False # set true to use CVP
ROI_CROPPING_R: 4  # set to 35 for ShapeStack
```
whether to use IN is specified by: `ARCH: 'rpin'`

**Special things about VIN**: As we mentioned in paper, VIN need a 'fixed' mapping between object identity and channel index. Current realb data does not have the same object_id for the same object *across video*. (The object id is the same only within a single video). Therefore I processed it and sent the link to you.

Finally, note that as I mentioned in readme, I'm not able to have a detailed performance by now and I'm sorry about that. Please let me know if you need any other information.

**Comment by dingmyu** [comment]
> Hi, here is the update [commit](https://github.com/HaozhiQi/RPIN/commit/69656d4e844998ab30032f1430c7c206e7427441). The entry point is the `configs/realb/rpin.yaml`.
> 
> ```
> USE_VIN_FEAT: False  # set true to use VIN; But VIN need some special configuration, see below.
> ROI_MASKING: False  # set true to use OM
> ROI_CROPPING: False # set true to use CVP
> ROI_CROPPING_R: 4  # set to 35 for ShapeStack
> ```
> 
> whether to use IN is specified by: `ARCH: 'rpin'`
> 
> **Special things about VIN**: As we mentioned in paper, VIN need a 'fixed' mapping between object identity and channel index. Current realb data does not have the same object_id for the same object _across video_. (The object id is the same only within a single video). Therefore I processed it and sent the link to you.
> 
> Finally, note that as I mentioned in readme, I'm not able to have a detailed performance by now and I'm sorry about that. Please let me know if you need any other information.

Hi Haozhi,
Cool! Thank you for your quick reply. I will try it soon.

Regards
