### ISSUE TITLE
load the /simb/test.hkl file error

### ISSUE THREAD

**Issue by return-sleep** [HaozhiQi/RPIN#6]
when i run simb/prepare_billiard.py:

OSError: [Errno 5] Can't read data (file read failed: time = Sun Dec  4 22:20:06 2022
, filename = 'Dataloader/simb/test.hkl', file descriptor = 4, errno = 5, error message = 'Input/output error', buf = 0x564eae5a1151, total read size = 907, bytes this sub-read = 907, bytes actually read = 18446744073709551615, offset = 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Dataloader/simb/prepare_billiard.py", line 73, in <module>
    main()
  File "Dataloader/simb/prepare_billiard.py", line 31, in main
    src_data = hickle.load(src_file)
  File "/remote-home/xhl/anaconda3/envs/gsgn/lib/python3.7/site-packages/hickle/hickle.py", line 387, in load
    raise ValueError("Provided argument 'file_obj' does not appear to be a valid hickle file! (%s)" % (error),error) from error
ValueError: ("Provided argument 'file_obj' does not appear to be a valid hickle file! ([Errno 5] Can't read data (file read failed: time = Sun Dec  4 22:20:06 2022\n, filename = 'Dataloader/simb/test.hkl', file descriptor = 4, errno = 5, error message = 'Input/output error', buf = 0x564eae5a1151, total read size = 907, bytes this sub-read = 907, bytes actually read = 18446744073709551615, offset = 0))", OSError(5, "Can't read data (file read failed: time = Sun Dec  4 22:20:06 2022\n, filename = 'Dataloader/simb/test.hkl', file descriptor = 4, errno = 5, error message = 'Input/output error', buf = 0x564eae5a1151, total read size = 907, bytes this sub-read = 907, bytes actually read = 18446744073709551615, offset = 0)"))

**Comment by HaozhiQi** [comment]
I think you are right. It seems the google drive will reject these requests in some cases.
```
Access denied with the following error:

 	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses.

You may still be able to access the file from the browser:

	 https://drive.google.com/uc?id=1ucTEMTyzWS1uaknrFU3gTpE3KnNlKAIf
```

For a detailed discussion, you can refer to [the discussion on gdown repo](https://github.com/wkentaro/gdown/issues/43).

In summary, I think you can either click the link to download the zip file, or you can [configure an access token](https://stackoverflow.com/questions/65312867/how-to-download-large-file-from-google-drive-from-terminal-gdown-doesnt-work) to download the file using `curl`.

I'm not sure how to fix this permenantly with google drive. I may need to change to another storage provider in the future.

**Comment by return-sleep** [comment]
Thanks for your reply~

 Actually, I directly downloaded the zip file of  simb dataset from the provided link (https://drive.google.com/uc?id=1ucTEMTyzWS1uaknrFU3gTpE3KnNlKAIf).  When I ran simb/prepare_billiard.py,  The error mentioned above occurred. I have tried some solutions to this issue, but they didn't work

May I ask about the version of hickle?  Or is there another format of dataset file， except hkl?

**Comment by HaozhiQi** [comment]
Hi @return-sleep,

I think this is because the original file is generated by an older version of hickle or h5py.

I'll work on a fix tomorrow.

**Comment by HaozhiQi** [comment]
Hi @return-sleep,

I managed to find my old conda environment, which shows the hickle version is `4.0.4` and `h5py` version is '2.10.0`. This is the version used to generate the data. So you can run the script using this version.

On the other hand, I re-generated another one with `hickle==5.0.2` and `h5py==3.1.0`. Here is the link: [train.hkl](https://drive.google.com/file/d/1A2oowQMODo_xcpUSLw9tDwRE9afXsOtw/view?usp=share_link) and [test.hkl](https://drive.google.com/file/d/1pE0eDZ2dcND6PVvBtK52PmfC1tph_Lm8/view?usp=share_link). You should be able to run the `prepare_billiard` script with this data

**Comment by return-sleep** [comment]
@HaozhiQi  Thanks for the update!
